deploy.sh, vue.config.js
=> feat: deploy

src/assets/styles/home-tabs.scss, src/assets/styles/main-input.scss, src/assets/styles/user-panel.scss, src/components/HomeTabs.vue, src/views/Login.vue, src/views/Register.vue
=> modify: resolve conflict

src/apis/followships.js, src/assets/styles/admin-card.scss, src/assets/styles/admin-main-page.scss, src/assets/styles/basic.scss, src/assets/styles/button.scss, src/assets/styles/colors.scss, src/assets/styles/footer.scss, src/assets/styles/header.scss, src/assets/styles/home-tabs.scss, src/assets/styles/main-input.scss, src/assets/styles/main-page.scss, src/assets/styles/main-tweet.scss, src/assets/styles/recommend-users.scss, src/assets/styles/reply-card.scss, src/assets/styles/reset.scss, src/assets/styles/side-bar.scss, src/assets/styles/tweet-card.scss, src/assets/styles/user-follow-card.scss, src/components/AdminTweets.vue, src/components/MainHeader.vue, src/components/MainTweet.vue, src/components/RecommendUsers.vue, src/components/SideBar.vue, src/components/SideBarAdmin.vue, src/components/TweetCard.vue, src/components/UserHeader.vue, src/router/index.js, src/views/TweetDetail.vue
1. 新增字體和字重變數並導用
2. 新增 recommendUsers 假資料串連和 isFollowed 變化
=> Feature main page api

src/apis/admin.js, src/apis/tweets.js, src/apis/users.js, src/assets/styles/tweet-card.scss, src/components/AdminTweets.vue, src/components/MainHeader.vue, src/components/MainTweet.vue, src/components/RecommendUsers.vue, src/components/ReplyCard.vue, src/components/TweetCard.vue, src/router/index.js, src/views/AdminTweets.vue, src/views/Main.vue, src/views/TweetDetail.vue, src/views/UserDetail.vue
1. 新增後台頁面GET & DELETE 推文
2. GET推薦使用者
3. 單一推文頁面 GET 推文資料 & 回覆資料
=> Feature main page api v2

src/apis/admin.js, src/assets/styles/reset.scss, src/views/AdminLogin.vue, src/views/Login.vue, src/views/Register.vue
1. 完成前台、後台登入驗證功能
2. 完成註冊頁面驗證功能
（剩下：當使用者因任何因素未成功建立帳號，欄位依然帶有原先使用者填寫的值）
3. error.response.data.message(一輩子記得要這樣拿資料)
=> feat: register, login

package-lock.json, package.json, src/assets/styles/form.scss, src/assets/styles/main-input.scss, src/components/AdminTweets.vue, src/utils/helpers.js, src/utils/mixins.js
1. 新增共用mixins(moment, emptyImage, showDescription)
2. 後台新增功能：需有提示才能刪除貼文
3. MainTweetInput給予border-bottom
=> feature: mixins(filters) and admin tweets

package-lock.json, package.json, src/apis/followships.js, src/apis/tweets.js, src/apis/users.js, src/assets/styles/modal.scss, src/components/AdminTweets.vue, src/components/MainTweet.vue, src/components/MainTweetInput.vue, src/components/MainTweetModal.vue, src/components/RecommendUsers.vue, src/components/ReplyCard.vue, src/components/SideBar.vue, src/components/TweetCard.vue, src/main.js, src/router/index.js, src/store/index.js, src/views/AdminTweets.vue, src/views/Login.vue, src/views/Main.vue, src/views/TweetDetail.vue, src/views/UserDetail.vue
=> Feature main page api v3

src/apis/admin.js, src/apis/users.js, src/assets/styles/admin-card.scss, src/assets/styles/admin-main-page.scss, src/components/AdminTweets.vue, src/components/AdminUsers.vue, src/components/SettingPanel.vue, src/views/AdminTweets.vue, src/views/AdminUsers.vue, src/views/Register.vue
=> feature: admin & setting

src/apis/users.js, src/assets/styles/form.scss, src/components/SettingPanel.vue, src/store/index.js, src/views/Main.vue, src/views/Setting.vue
=> feature:setting function

src/apis/tweets.js, src/assets/images/tweet_liked.svg, src/assets/styles/main-input.scss, src/components/MainReplyModal.vue, src/components/MainTweet.vue, src/components/MainTweetModal.vue, src/components/TweetCard.vue, src/router/index.js, src/store/index.js, src/views/AdminLogin.vue, src/views/Follow copy.vue, src/views/Main.vue, src/views/TweetDetail.vue, src/views/UserDetail.vue
=> Feature user page api v1

src/assets/styles/button.scss, src/assets/styles/main-modal.scss, src/assets/styles/modal.scss, src/assets/styles/user-panel.scss, src/components/AdminTweets.vue, src/components/AdminUsers.vue, src/components/MainTweetModal.vue, src/components/SideBarAdmin.vue, src/components/UserEditModal.vue, src/components/UserPanel.vue, src/router/index.js, src/views/AdminLogin.vue, src/views/AdminTweets.vue, src/views/AdminUsers.vue, src/views/UserDetail.vue
=> modify: sign and feature: userDetail

src/router/index.js
=> modify: router problem

src/assets/styles/main-input.scss, src/assets/styles/main-page.scss, src/assets/styles/modal.scss, src/components/HomeTabs.vue, src/components/MainHeader.vue, src/components/MainReplyModal.vue, src/components/MainTweet.vue, src/components/MainTweetInput.vue, src/components/MainTweetModal.vue, src/components/RecommendUsers.vue, src/components/ReplyCard.vue, src/components/SideBar.vue, src/components/TweetCard.vue, src/components/UserFollowCard.vue, src/components/UserPanel.vue, src/router/index.js, src/store/index.js, src/utils/helpers.js, src/views/Follower.vue, src/views/Following.vue, src/views/Main.vue, src/views/Setting.vue, src/views/TweetDetail.vue, src/views/UserDetail.vue
1. 完成追隨者頁面，正在追蹤待補
2. 完成個人詳細頁面的標籤切換
3. 完成各頁面的發文
4. 完成各頁面的回覆
=> Feature user page api v2

src/apis/users.js, src/assets/styles/colors.scss, src/assets/styles/form.scss, src/assets/styles/modal.scss, src/components/SettingPanel.vue, src/components/SideBar.vue, src/components/UserEditModal.vue, src/components/UserPanel.vue, src/main.js, src/utils/helpers.js, src/views/Register.vue, src/views/Setting.vue, src/views/UserDetail.vue
=> feature: edit and upload profile

src/components/SideBar.vue, src/views/UserDetail.vue
=> modify: conflicts

src/views/UserDetail.vue
=> modify: prepare to PR

src/assets/styles/footer.scss, src/assets/styles/main.scss, src/assets/styles/modal.scss, src/assets/styles/side-bar.scss, src/assets/styles/spinner.scss, src/components/FooterAdmin.vue, src/components/RecommendUsers.vue, src/components/SideBar.vue, src/components/Spinner.vue, src/views/AdminTweets.vue, src/views/AdminUsers.vue, src/views/Follow.vue, src/views/Main.vue, src/views/TweetDetail.vue, src/views/UserDetail.vue
=> feat: add Spinner

src/assets/styles/modal.scss, src/assets/styles/user-panel.scss, src/components/UserEditModal.vue, src/components/UserPanel.vue, src/views/UserDetail.vue
=> modify: upload photos

src/assets/images/tweet_liked.svg, src/assets/styles/button.scss, src/assets/styles/form.scss, src/assets/styles/home-tabs.scss, src/assets/styles/main-tweet.scss, src/components/HomeTabs.vue, src/components/MainReplyModal.vue, src/components/MainTweet.vue, src/components/MainTweetModal.vue, src/components/RecommendUsers.vue, src/components/SettingPanel.vue, src/components/TweetCard.vue, src/components/UserEditModal.vue, src/components/UserFollowCard.vue, src/components/UserPanel.vue, src/views/Setting.vue, src/views/UserDetail.vue
=> Refactor pages v1

src/assets/styles/basic.scss, src/assets/styles/button.scss, src/assets/styles/colors.scss, src/assets/styles/home-tabs.scss, src/assets/styles/main-page.scss, src/assets/styles/main-tweet.scss, src/assets/styles/modal.scss, src/assets/styles/recommend-users.scss, src/assets/styles/side-bar.scss, src/assets/styles/tweet-card.scss, src/assets/styles/user-panel.scss, src/components/MainReplyModal.vue, src/components/MainTweetModal.vue, src/components/RecommendUsers.vue, src/components/SideBar.vue, src/components/SideBarAdmin.vue, src/components/TweetCard.vue, src/components/UserEditModal.vue, src/components/UserFollowCard.vue, src/components/UserPanel.vue, src/router/index.js, src/views/Follow.vue, src/views/Main.vue, src/views/Setting.vue, src/views/TweetDetail.vue, src/views/UserDetail.vue
1. 新增推文和推薦雖隨者卡片的hover效果
2. 新增正在追隨按紐的hover換字效果
3. 新增進入每一個頁面的使用者身分驗證
4. 修正modal的開關邏輯
=> Refactor pages v2

src/apis/users.js, src/assets/styles/basic.scss, src/assets/styles/form.scss, src/assets/styles/main-modal.scss, src/assets/styles/main.scss, src/assets/styles/modal.scss, src/assets/styles/not-found.scss, src/assets/styles/side-bar.scss, src/assets/styles/sweet-alert.scss, src/assets/styles/user-panel.scss, src/components/AdminTweets.vue, src/components/AdminUsers.vue, src/components/MainHeader.vue, src/components/MainReplyModal.vue, src/components/MainTweet.vue, src/components/MainTweetInput.vue, src/components/MainTweetModal.vue, src/components/RecommendUsers.vue, src/components/ReplyCard.vue, src/components/SettingPanel.vue, src/components/TweetCard.vue, src/components/UserEditModal.vue, src/components/UserFollowCard.vue, src/components/UserPanel.vue, src/views/AdminLogin.vue, src/views/Login.vue, src/views/NotFound.vue, src/views/Register.vue, src/views/UserDetail.vue
1. 移除封面照片功能
2. 重構表單邏輯
3. 重構RWD與修正破版
=> feature: remove cover photo and refactor: RWD

src/assets/styles/button.scss, src/assets/styles/colors.scss, src/assets/styles/header.scss, src/assets/styles/modal.scss, src/assets/styles/user-panel.scss, src/components/MainHeader.vue, src/components/MainReplyModal.vue, src/components/MainTweetModal.vue, src/components/UserHeader.vue, src/views/Follow.vue, src/views/Main.vue, src/views/Setting.vue, src/views/TweetDetail.vue, src/views/UserDetail.vue
1. 新增modal框的header
2. 新增按紐形式
3. 調整個人主頁按紐RWD
4. 調整所有頁面的header
=> Refoctor pages v3

README.md, src/assets/styles/home-tabs.scss, src/assets/styles/modal.scss, src/assets/styles/user-panel.scss, src/components/UserEditModal.vue
1. 微調UserPanel RWD 間距問題
2. 刪除封面照片後跳提示通知成功
=> modify: RWD and toast

src/assets/styles/admin-tweet-card.scss, src/assets/styles/button.scss, src/assets/styles/main-tweet.scss, src/assets/styles/modal.scss, src/assets/styles/side-bar.scss, src/assets/styles/tweet-card.scss, src/assets/styles/user-follow-card.scss, src/components/MainReplyModal.vue, src/components/MainTweetModal.vue, src/components/SideBarAdmin.vue, src/components/TweetCard.vue, src/views/Follow.vue, src/views/Main.vue, src/views/UserDetail.vue
1. 重構推特卡片 CSS 並新增 icon 的 hover
2. 修復 Admin 頁面 Sidebar hover 顯示錯誤
3. 修復 Main 頁面新增貼文後不會自動更新
4. 新增推文儲存至 localStorage
=> feat: add icon hover

src/assets/styles/form.scss, src/assets/styles/main-modal.scss, src/assets/styles/main-tweet.scss, src/assets/styles/modal.scss, src/assets/styles/side-bar.scss, src/components/MainReplyInput.vue, src/components/MainTweet.vue, src/utils/mixins.js, src/views/Main.vue, src/views/TweetDetail.vue
1. 新增推特詳細頁面的詳細時間格式
2. 新增手機版回覆按紐的 toggle
3. 修改主要按紐的 hover 效果
=> Refactor pages v5
